import { ids, restaurants } from '../data/restaurants';
export type Vote={id:string;name:string;ranking:string[];created_at:string;updated_at:string};
const url=import.meta.env?.VITE_SUPABASE_URL?.replace(/\/$/,'');
const key=import.meta.env?.VITE_SUPABASE_ANON_KEY;
export const isLive=Boolean(url && key && !url.includes('your-project') && (key.startsWith('eyJ') || key.startsWith('sb_publishable_')));
export const normalizeName=(name:string)=>name.trim().replace(/\s+/g,' ');
export function validRanking(value:unknown):value is string[]{return Array.isArray(value)&&value.length===ids.length&&new Set(value).size===ids.length&&value.every(id=>ids.includes(id))}
export function leaderboard(votes:Vote[]){return restaurants.map(r=>{const positions=votes.filter(v=>validRanking(v.ranking)).map(v=>v.ranking.indexOf(r.id)+1);return {...r,points:positions.reduce((sum,p)=>sum+ids.length+1-p,0),firsts:positions.filter(p=>p===1).length,average:positions.length?positions.reduce((a,b)=>a+b,0)/positions.length:0}}).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name))}
function token(){let value=localStorage.getItem('birthday-owner-token');if(!value){value=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');localStorage.setItem('birthday-owner-token',value)}return value}
async function request(path:string,options:RequestInit={}){const res=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key!,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(12000)});if(!res.ok){const data=await res.json().catch(()=>({})) as {message?:string;details?:string;hint?:string;code?:string};if(data.message?.includes('name is already'))throw new Error('That name is already in use on another browser. Use a distinguishing name, such as your surname or initial.');const reason=[data.message,data.details,data.hint].filter(Boolean).join(' — ');throw new Error(reason?`Supabase rejected the vote: ${reason} (HTTP ${res.status})`:`Voting service returned HTTP ${res.status}. Check that the Supabase SQL migration has been run.`)}return res.json()}
export async function readVotes():Promise<Vote[]>{const data=isLive?await request('birthday_votes?select=id,name,ranking,created_at,updated_at&order=created_at.asc'):JSON.parse(localStorage.getItem('birthday-demo-votes')||'[]');if(!Array.isArray(data))throw new Error('Unexpected vote data');return data.filter(v=>typeof v.name==='string'&&validRanking(v.ranking))}
export async function saveVote(name:string,ranking:string[]):Promise<void>{name=normalizeName(name);if(!name||name.length>60||!validRanking(ranking))throw new Error('Enter a name and rank all six restaurants once.');if(isLive){await request('rpc/submit_birthday_vote',{method:'POST',body:JSON.stringify({p_name:name,p_ranking:ranking,p_token:token()})});return}const votes=await readVotes();const old=votes.find(v=>v.name.toLocaleLowerCase()===name.toLocaleLowerCase());const now=new Date().toISOString();const vote:Vote={id:old?.id||crypto.randomUUID(),name,ranking,created_at:old?.created_at||now,updated_at:now};localStorage.setItem('birthday-demo-votes',JSON.stringify([...votes.filter(v=>v.id!==vote.id),vote]));}
